### ISSUE TITLE
Critical issue: widget state not updated

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-windows#68] opened 2017-07-27 19:07 UTC
If you change the state with another UI for example of a light, the state is not updated in Windows app. Switching to the main page and then returning to the sub-page changes nothing.
It looks like the app is not "listening" to events coming from the server.

Windows 10 PC

**Comment by NicoVermeir** [comment] 2017-07-28 08:36
duplicate of #36

**Closed as completed by NicoVermeir** 2017-07-28 08:36 UTC
